version: '3.3'

services:
  db:
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  
  backend:
    image: viktor888/backend_foodgram:latest
    restart: always
    depends_on:
      - db
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    env_file:
      - ./.env

  frontend:
    image: viktor888/frontend_foodgram:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend

volumes:
  postgres_data:
  static_value:
  media_value:
