# Generated by Django 3.2.9 on 2023-04-17 11:27

import api.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_options_alter_recipe_cooking_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=200, validators=[api.validator.validate_alpha], verbose_name='Название'),
        ),
    ]
